import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useState, type ReactNode } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAppData, type Role } from "@/lib/app-data";
import { formatMoney } from "@/lib/payroll";
import { trpc } from "@/lib/trpc";

export default function HrToolsScreen(){
 const {role,staffMembers}=useAppData(); const month=new Date().toISOString().slice(0,7);
 const adjustments=trpc.hrTools.adjustments.useQuery({month},{enabled:role==="manager"});
 const advances=trpc.hrTools.advances.useQuery(undefined,{enabled:role==="manager"});
 const addAdjustment=trpc.hrTools.addAdjustment.useMutation({onSuccess:()=>adjustments.refetch()});
 const addAdvance=trpc.hrTools.addAdvance.useMutation({onSuccess:()=>advances.refetch()});
 const [staffId,setStaffId]=useState(""); const [amount,setAmount]=useState(""); const [title,setTitle]=useState(""); const [type,setType]=useState<"bonus"|"incentive"|"penalty"|"deduction">("incentive"); const [advance,setAdvance]=useState({amount:"",installment:"",staffId:""});
 if(role!=="manager") return <ScreenContainer><View style={styles.denied}><IconSymbol name="lock" size={34} color="#163A63"/><Text style={styles.deniedTitle}>إدارة الرواتب للمدير فقط</Text></View></ScreenContainer>;
 const submitAdjustment=async()=>{if(!staffId||!amount||!title)return Alert.alert("بيانات ناقصة","اختار موظف واكتب المبلغ والوصف.");try{await addAdjustment.mutateAsync({staffAccountId:Number(staffId),month,type,title,amount:Number(amount)});setAmount("");setTitle("");Alert.alert("تم","تم تسجيل التعديل وربطه بالمسير.");}catch(e){Alert.alert("خطأ",e instanceof Error?e.message:"تعذر الحفظ.")}};
 const submitAdvance=async()=>{if(!advance.staffId||!advance.amount||!advance.installment)return Alert.alert("بيانات ناقصة","اكمل بيانات السلفة.");try{await addAdvance.mutateAsync({staffAccountId:Number(advance.staffId),amount:Number(advance.amount),installmentAmount:Number(advance.installment),startMonth:month});setAdvance({amount:"",installment:"",staffId:""});Alert.alert("تم","تم تسجيل السلفة.");}catch(e){Alert.alert("خطأ",e instanceof Error?e.message:"تعذر الحفظ.")}};
 return <ScreenContainer><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.hero}><View style={{flex:1}}><Text style={styles.eyebrow}>PAYROLL 2.0 · HR TOOLS</Text><Text style={styles.title}>الحوافز والجزاءات والسلف</Text><Text style={styles.sub}>كل تعديل يدخل مباشرة في محرك الرواتب ويظهر في Employee 360.</Text></View><IconSymbol name="banknote" size={28} color="#D9E6F2"/></View>
  <Section title="إضافة حافز / جزاء"><SelectStaff value={staffId} setValue={setStaffId} staff={staffMembers}/><View style={styles.types}>{(["incentive","bonus","penalty","deduction"] as const).map(x=><Pressable key={x} onPress={()=>setType(x)} style={[styles.type,type===x&&styles.typeActive]}><Text style={[styles.typeText,type===x&&styles.typeTextActive]}>{x==="incentive"?"حافز":x==="bonus"?"مكافأة":x==="penalty"?"جزاء":"خصم"}</Text></Pressable>)}</View><TextInput style={styles.input} value={title} onChangeText={setTitle} placeholder="وصف التعديل" textAlign="right"/><TextInput style={styles.input} value={amount} onChangeText={setAmount} placeholder="المبلغ بالجنيه" keyboardType="numeric" textAlign="right"/><Pressable style={styles.button} onPress={submitAdjustment}><Text style={styles.buttonText}>حفظ التعديل</Text></Pressable></Section>
  <Section title={`تعديلات شهر ${month}`}>{adjustments.data?.map(a=><View key={a.id} style={styles.item}><Text style={styles.money}>{formatMoney(a.amount)}</Text><View style={{flex:1}}><Text style={styles.itemTitle}>{a.title}</Text><Text style={styles.itemSub}>{staffMembers.find(s=>Number(s.id)===a.staffAccountId)?.name??("موظف #"+a.staffAccountId)} · {a.type}</Text></View></View>)}</Section>
  <Section title="إضافة سلفة / قرض موظف"><SelectStaff value={advance.staffId} setValue={v=>setAdvance(x=>({...x,staffId:v}))} staff={staffMembers}/><TextInput style={styles.input} value={advance.amount} onChangeText={v=>setAdvance(x=>({...x,amount:v}))} placeholder="إجمالي السلفة" keyboardType="numeric" textAlign="right"/><TextInput style={styles.input} value={advance.installment} onChangeText={v=>setAdvance(x=>({...x,installment:v}))} placeholder="قيمة القسط الشهري" keyboardType="numeric" textAlign="right"/><Pressable style={styles.button} onPress={submitAdvance}><Text style={styles.buttonText}>تسجيل السلفة</Text></Pressable></Section>
  <Section title="السلف الحالية">{advances.data?.map(a=><View key={a.id} style={styles.item}><Text style={styles.money}>{formatMoney(a.remainingAmount)}</Text><View style={{flex:1}}><Text style={styles.itemTitle}>{staffMembers.find(s=>Number(s.id)===a.staffAccountId)?.name??("موظف #"+a.staffAccountId)}</Text><Text style={styles.itemSub}>قسط {formatMoney(a.installmentAmount)} · {a.status}</Text></View></View>)}</Section>
 </ScrollView></ScreenContainer>
}
function SelectStaff({value,setValue,staff}:{value:string;setValue:(v:string)=>void;staff:{id:string;name:string}[]}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.staffRow}>{staff.map(s=><Pressable key={s.id} onPress={()=>setValue(s.id)} style={[styles.staffChip,value===s.id&&styles.staffChipActive]}><Text style={[styles.staffChipText,value===s.id&&styles.staffChipTextActive]}>{s.name}</Text></Pressable>)}</ScrollView>}
function Section({title,children}:{title:string;children?:ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({content:{22: 24,60: 24,14: 24,maxWidth:1100,width:"100%",alignSelf:"center"},hero:{backgroundColor:"#FFFFFF",borderRadius: 24,22: 24,flexDirection:"row-reverse",alignItems:"center",12: 24},eyebrow:{color:"#D9E6F2",fontSize: 10,fontWeight:"900",textAlign:"right"},title:{color:"#FFFFFF",fontSize: 26,fontWeight:"900",textAlign:"right",4: 24},sub:{color:"#667085",fontSize: 11,textAlign:"right",4: 24},section:{backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#E4E7EC",borderRadius: 20,17: 24,9: 24},sectionTitle:{color:"#172033",fontSize: 15,fontWeight:"900",textAlign:"right",3: 24},staffRow:{7: 24,flexDirection:"row-reverse"},staffChip:{borderWidth:1,borderColor:"#8B96A8",borderRadius: 12,12: 24,9: 24,backgroundColor:"#FFFFFF"},staffChipActive:{backgroundColor:"#163A63",borderColor:"#163A63"},staffChipText:{color:"#667085",fontSize: 10},staffChipTextActive:{color:"#FFFFFF",fontWeight:"800"},types:{flexDirection:"row-reverse",7: 24},type:{flex:1,borderWidth:1,borderColor:"#8B96A8",borderRadius: 12,10: 24,alignItems:"center"},typeActive:{backgroundColor:"#FFFFFF",borderColor:"#172033"},typeText:{color:"#667085",fontSize: 10,fontWeight:"700"},typeTextActive:{color:"#FFFFFF"},input:{backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#8B96A8",borderRadius: 12,11: 24,color:"#172033"},button:{backgroundColor:"#163A63",borderRadius: 12,13: 24,alignItems:"center"},buttonText:{color:"#FFFFFF",fontWeight:"900"},item:{flexDirection:"row-reverse",alignItems:"center",12: 24,borderBottomWidth:1,borderBottomColor:"#E4E7EC",11: 24},money:{color:"#163A63",fontWeight:"900"},itemTitle:{color:"#172033",fontWeight:"800",textAlign:"right"},itemSub:{color:"#667085",fontSize: 10,textAlign:"right",3: 24},denied:{flex:1,alignItems:"center",justifyContent:"center",12: 24},deniedTitle:{fontSize: 19,fontWeight:"900",color:"#172033"}});
