import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useState, type ReactNode } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAppData, type Role } from "@/lib/app-data";
import { formatMoney } from "@/lib/payroll";
import { trpc } from "@/lib/trpc";

export default function HrToolsScreen(){
 const {role,staffMembers}=useAppData(); const month=new Date().toISOString().slice(0,7);
 const adjustments=trpc.hrTools.adjustments.useQuery({month},{enabled:role==="manager"});
 const advances=trpc.hrTools.advances.useQuery(undefined,{enabled:role==="manager"});
 const addAdjustment=trpc.hrTools.addAdjustment.useMutation({onSuccess:()=>adjustments.refetch()});
 const addAdvance=trpc.hrTools.addAdvance.useMutation({onSuccess:()=>advances.refetch()});
 const [staffId,setStaffId]=useState(""); const [amount,setAmount]=useState(""); const [title,setTitle]=useState(""); const [type,setType]=useState<"bonus"|"incentive"|"penalty"|"deduction">("incentive"); const [advance,setAdvance]=useState({amount:"",installment:"",staffId:""});
 if(role!=="manager") return <ScreenContainer><View style={styles.denied}><IconSymbol name="lock" size={34} color="#2563EB"/><Text style={styles.deniedTitle}>إدارة الرواتب للمدير فقط</Text></View></ScreenContainer>;
 const submitAdjustment=async()=>{if(!staffId||!amount||!title)return Alert.alert("بيانات ناقصة","اختار موظف واكتب المبلغ والوصف.");try{await addAdjustment.mutateAsync({staffAccountId:Number(staffId),month,type,title,amount:Number(amount)});setAmount("");setTitle("");Alert.alert("تم","تم تسجيل التعديل وربطه بالمسير.");}catch(e){Alert.alert("خطأ",e instanceof Error?e.message:"تعذر الحفظ.")}};
 const submitAdvance=async()=>{if(!advance.staffId||!advance.amount||!advance.installment)return Alert.alert("بيانات ناقصة","اكمل بيانات السلفة.");try{await addAdvance.mutateAsync({staffAccountId:Number(advance.staffId),amount:Number(advance.amount),installmentAmount:Number(advance.installment),startMonth:month});setAdvance({amount:"",installment:"",staffId:""});Alert.alert("تم","تم تسجيل السلفة.");}catch(e){Alert.alert("خطأ",e instanceof Error?e.message:"تعذر الحفظ.")}};
 return <ScreenContainer><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.hero}><View style={{flex:1}}><Text style={styles.eyebrow}>PAYROLL 2.0 · HR TOOLS</Text><Text style={styles.title}>الحوافز والجزاءات والسلف</Text><Text style={styles.sub}>كل تعديل يدخل مباشرة في محرك الرواتب ويظهر في Employee 360.</Text></View><IconSymbol name="banknote" size={28} color="#93C5FD"/></View>
  <Section title="إضافة حافز / جزاء"><SelectStaff value={staffId} setValue={setStaffId} staff={staffMembers}/><View style={styles.types}>{(["incentive","bonus","penalty","deduction"] as const).map(x=><Pressable key={x} onPress={()=>setType(x)} style={[styles.type,type===x&&styles.typeActive]}><Text style={[styles.typeText,type===x&&styles.typeTextActive]}>{x==="incentive"?"حافز":x==="bonus"?"مكافأة":x==="penalty"?"جزاء":"خصم"}</Text></Pressable>)}</View><TextInput style={styles.input} value={title} onChangeText={setTitle} placeholder="وصف التعديل" textAlign="right"/><TextInput style={styles.input} value={amount} onChangeText={setAmount} placeholder="المبلغ بالجنيه" keyboardType="numeric" textAlign="right"/><Pressable style={styles.button} onPress={submitAdjustment}><Text style={styles.buttonText}>حفظ التعديل</Text></Pressable></Section>
  <Section title={`تعديلات شهر ${month}`}>{adjustments.data?.map(a=><View key={a.id} style={styles.item}><Text style={styles.money}>{formatMoney(a.amount)}</Text><View style={{flex:1}}><Text style={styles.itemTitle}>{a.title}</Text><Text style={styles.itemSub}>{staffMembers.find(s=>Number(s.id)===a.staffAccountId)?.name??("موظف #"+a.staffAccountId)} · {a.type}</Text></View></View>)}</Section>
  <Section title="إضافة سلفة / قرض موظف"><SelectStaff value={advance.staffId} setValue={v=>setAdvance(x=>({...x,staffId:v}))} staff={staffMembers}/><TextInput style={styles.input} value={advance.amount} onChangeText={v=>setAdvance(x=>({...x,amount:v}))} placeholder="إجمالي السلفة" keyboardType="numeric" textAlign="right"/><TextInput style={styles.input} value={advance.installment} onChangeText={v=>setAdvance(x=>({...x,installment:v}))} placeholder="قيمة القسط الشهري" keyboardType="numeric" textAlign="right"/><Pressable style={styles.button} onPress={submitAdvance}><Text style={styles.buttonText}>تسجيل السلفة</Text></Pressable></Section>
  <Section title="السلف الحالية">{advances.data?.map(a=><View key={a.id} style={styles.item}><Text style={styles.money}>{formatMoney(a.remainingAmount)}</Text><View style={{flex:1}}><Text style={styles.itemTitle}>{staffMembers.find(s=>Number(s.id)===a.staffAccountId)?.name??("موظف #"+a.staffAccountId)}</Text><Text style={styles.itemSub}>قسط {formatMoney(a.installmentAmount)} · {a.status}</Text></View></View>)}</Section>
 </ScrollView></ScreenContainer>
}
function SelectStaff({value,setValue,staff}:{value:string;setValue:(v:string)=>void;staff:{id:string;name:string}[]}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.staffRow}>{staff.map(s=><Pressable key={s.id} onPress={()=>setValue(s.id)} style={[styles.staffChip,value===s.id&&styles.staffChipActive]}><Text style={[styles.staffChipText,value===s.id&&styles.staffChipTextActive]}>{s.name}</Text></Pressable>)}</ScrollView>}
function Section({title,children}:{title:string;children?:ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({content:{padding:22,paddingBottom:60,gap:14,maxWidth:1100,width:"100%",alignSelf:"center"},hero:{backgroundColor:"#0B1220",borderRadius:25,padding:22,flexDirection:"row-reverse",alignItems:"center",gap:12},eyebrow:{color:"#93C5FD",fontSize:9,fontWeight:"900",textAlign:"right"},title:{color:"#FFF",fontSize:25,fontWeight:"900",textAlign:"right",marginTop:4},sub:{color:"#94A3B8",fontSize:11,textAlign:"right",marginTop:4},section:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#E2E8F0",borderRadius:20,padding:17,gap:9},sectionTitle:{color:"#0F172A",fontSize:16,fontWeight:"900",textAlign:"right",marginBottom:3},staffRow:{gap:7,flexDirection:"row-reverse"},staffChip:{borderWidth:1,borderColor:"#CBD5E1",borderRadius:11,paddingHorizontal:12,paddingVertical:9,backgroundColor:"#F8FAFC"},staffChipActive:{backgroundColor:"#2563EB",borderColor:"#2563EB"},staffChipText:{color:"#334155",fontSize:10},staffChipTextActive:{color:"#FFF",fontWeight:"800"},types:{flexDirection:"row-reverse",gap:7},type:{flex:1,borderWidth:1,borderColor:"#CBD5E1",borderRadius:10,padding:10,alignItems:"center"},typeActive:{backgroundColor:"#0F172A",borderColor:"#0F172A"},typeText:{color:"#334155",fontSize:10,fontWeight:"700"},typeTextActive:{color:"#FFF"},input:{backgroundColor:"#F8FAFC",borderWidth:1,borderColor:"#CBD5E1",borderRadius:11,padding:11,color:"#0F172A"},button:{backgroundColor:"#2563EB",borderRadius:12,padding:13,alignItems:"center"},buttonText:{color:"#FFF",fontWeight:"900"},item:{flexDirection:"row-reverse",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#F1F5F9",paddingVertical:11},money:{color:"#2563EB",fontWeight:"900"},itemTitle:{color:"#0F172A",fontWeight:"800",textAlign:"right"},itemSub:{color:"#64748B",fontSize:10,textAlign:"right",marginTop:3},denied:{flex:1,alignItems:"center",justifyContent:"center",gap:12},deniedTitle:{fontSize:19,fontWeight:"900",color:"#0F172A"}});
