import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { trpc } from "@/lib/trpc";

export default function NotificationsScreen(){
 const q=trpc.notifications.list.useQuery();
 const read=trpc.notifications.read.useMutation({onSuccess:()=>q.refetch()});
 return <ScreenContainer><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.header}><View><Text style={styles.eyebrow}>WORKSPACE · ALERTS</Text><Text style={styles.title}>الإشعارات</Text><Text style={styles.sub}>كل تحديثات الطلبات والحضور والرواتب في مكان واحد.</Text></View><View style={styles.icon}><IconSymbol name="notifications" size={22} color="#2563EB"/></View></View>
  {q.isLoading?<View style={styles.state}><ActivityIndicator color="#2563EB"/></View>:q.data?.length? q.data.map(n=><Pressable key={n.id} onPress={()=>!n.readAt&&read.mutate({id:n.id})} style={[styles.card,!n.readAt&&styles.unread]}><View style={styles.dotWrap}><View style={[styles.dot,{backgroundColor:n.readAt?"#CBD5E1":"#2563EB"}]}/></View><View style={styles.copy}><View style={styles.row}><Text style={styles.date}>{n.createdAt?new Date(n.createdAt).toLocaleString("ar-EG"):""}</Text><Text style={styles.cardTitle}>{n.title}</Text></View><Text style={styles.body}>{n.body}</Text>{!n.readAt&&<Text style={styles.mark}>اضغط لتحديد كمقروء</Text>}</View></Pressable>):<View style={styles.empty}><IconSymbol name="checkmark" size={28} color="#059669"/><Text style={styles.emptyTitle}>مفيش إشعارات جديدة</Text><Text style={styles.emptyText}>أول ما يحصل تحديث مهم هيظهر هنا.</Text></View>}
 </ScrollView></ScreenContainer>
}
const styles=StyleSheet.create({content:{padding:22,paddingBottom:60,gap:12,maxWidth:900,width:"100%",alignSelf:"center"},header:{backgroundColor:"#0B1220",borderRadius:24,padding:20,flexDirection:"row-reverse",alignItems:"center",gap:14},eyebrow:{color:"#93C5FD",fontSize:9,fontWeight:"900",textAlign:"right"},title:{color:"#FFF",fontSize:27,fontWeight:"900",textAlign:"right",marginTop:4},sub:{color:"#94A3B8",fontSize:11,textAlign:"right",marginTop:4},icon:{width:50,height:50,borderRadius:16,backgroundColor:"#DBEAFE",alignItems:"center",justifyContent:"center"},card:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#E2E8F0",borderRadius:18,padding:15,flexDirection:"row-reverse",gap:10},unread:{borderColor:"#93C5FD",backgroundColor:"#F8FBFF"},dotWrap:{width:10,paddingTop:5},dot:{width:8,height:8,borderRadius:4},copy:{flex:1},row:{flexDirection:"row-reverse",justifyContent:"space-between",gap:10},cardTitle:{color:"#0F172A",fontWeight:"900",fontSize:13,textAlign:"right",flex:1},date:{color:"#94A3B8",fontSize:9},body:{color:"#475569",fontSize:11,lineHeight:18,textAlign:"right",marginTop:6},mark:{color:"#2563EB",fontSize:9,fontWeight:"800",textAlign:"right",marginTop:7},state:{padding:40,alignItems:"center"},empty:{backgroundColor:"#ECFDF5",borderRadius:20,padding:25,alignItems:"center",gap:8},emptyTitle:{color:"#047857",fontSize:16,fontWeight:"900"},emptyText:{color:"#64748B",fontSize:11}});
