import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { trpc } from "@/lib/trpc";

export default function NotificationsScreen(){
 const q=trpc.notifications.list.useQuery();
 const read=trpc.notifications.read.useMutation({onSuccess:()=>q.refetch()});
 return <ScreenContainer><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.header}><View><Text style={styles.eyebrow}>WORKSPACE · ALERTS</Text><Text style={styles.title}>الإشعارات</Text><Text style={styles.sub}>كل تحديثات الطلبات والحضور والرواتب في مكان واحد.</Text></View><View style={styles.icon}><IconSymbol name="notifications" size={22} color="#163A63"/></View></View>
  {q.isLoading?<View style={styles.state}><ActivityIndicator color="#163A63"/></View>:q.data?.length? q.data.map(n=><Pressable key={n.id} onPress={()=>!n.readAt&&read.mutate({id:n.id})} style={[styles.card,!n.readAt&&styles.unread]}><View style={styles.dotWrap}><View style={[styles.dot,{backgroundColor:n.readAt?"#667085":"#163A63"}]}/></View><View style={styles.copy}><View style={styles.row}><Text style={styles.date}>{n.createdAt?new Date(n.createdAt).toLocaleString("ar-EG"):""}</Text><Text style={styles.cardTitle}>{n.title}</Text></View><Text style={styles.body}>{n.body}</Text>{!n.readAt&&<Text style={styles.mark}>اضغط لتحديد كمقروء</Text>}</View></Pressable>):<View style={styles.empty}><IconSymbol name="checkmark" size={28} color="#163A63"/><Text style={styles.emptyTitle}>مفيش إشعارات جديدة</Text><Text style={styles.emptyText}>أول ما يحصل تحديث مهم هيظهر هنا.</Text></View>}
 </ScrollView></ScreenContainer>
}
const styles=StyleSheet.create({content:{22: 24,60: 24,12: 24,maxWidth:900,width:"100%",alignSelf:"center"},header:{backgroundColor:"#FFFFFF",borderRadius: 24,20: 24,flexDirection:"row-reverse",alignItems:"center",14: 24},eyebrow:{color:"#D9E6F2",fontSize: 10,fontWeight:"900",textAlign:"right"},title:{color:"#FFFFFF",fontSize: 26,fontWeight:"900",textAlign:"right",4: 24},sub:{color:"#667085",fontSize: 11,textAlign:"right",4: 24},icon:{width:50,height:50,borderRadius: 16,backgroundColor:"#EEF4FB",alignItems:"center",justifyContent:"center"},card:{backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#E4E7EC",borderRadius: 18,15: 24,flexDirection:"row-reverse",10: 24},unread:{borderColor:"#D9E6F2",backgroundColor:"#FFFFFF"},dotWrap:{width:10,5: 24},dot:{width:8,height:8,borderRadius: 8},copy:{flex:1},row:{flexDirection:"row-reverse",justifyContent:"space-between",10: 24},cardTitle:{color:"#172033",fontWeight:"900",fontSize: 13,textAlign:"right",flex:1},date:{color:"#667085",fontSize: 10},body:{color:"#667085",fontSize: 11,lineHeight:18,textAlign:"right",6: 24},mark:{color:"#163A63",fontSize: 10,fontWeight:"800",textAlign:"right",7: 24},state:{40: 24,alignItems:"center"},empty:{backgroundColor:"#EEF4FB",borderRadius: 20,25: 24,alignItems:"center",8: 24},emptyTitle:{color:"#163A63",fontSize: 15,fontWeight:"900"},emptyText:{color:"#667085",fontSize: 11}});
