import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { ReactNode } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { PageHeader, SectionTitle, StatusBadge, SurfaceCard } from "@/components/ui/design-system";
import { useAppData } from "@/lib/app-data";
import { formatMoney } from "@/lib/payroll";
import { trpc } from "@/lib/trpc";

const month=new Date().toISOString().slice(0,7);
export default function PayrollScreen(){
 const {role,employee,payroll}=useAppData();
 const isAdmin=role==="manager";
 const query=trpc.payroll.list.useQuery({month},{enabled:isAdmin});
 const generate=trpc.payroll.generate.useMutation({onSuccess:()=>query.refetch()});
 const approve=trpc.payroll.approve.useMutation({onSuccess:()=>query.refetch()});
 const adjustments=trpc.hrTools.adjustments.useQuery({month},{enabled:isAdmin});
 const advances=trpc.hrTools.advances.useQuery(undefined,{enabled:isAdmin});
 if(query.isLoading&&isAdmin)return <ScreenContainer><View style={styles.state}><ActivityIndicator color="#5B9BFF"/><Text>جاري تحميل مسير الرواتب...</Text></View></ScreenContainer>;
 const rows=query.data??[];
 const total=rows.reduce((s,r)=>s+r.netSalary,0);
 return <ScreenContainer><ScrollView contentContainerStyle={styles.content}>
  <PageHeader eyebrow={`PAYROLL CENTER · ${month}`} title="الرواتب" subtitle="محرك رواتب مرتبط بالحضور والتأخير والغياب." icon="banknote" />
  <View style={styles.hero}><View><Text style={styles.kicker}>NET PAYROLL</Text><Text style={styles.heroValue}>{formatMoney(isAdmin?total:payroll.net)}</Text><Text style={styles.heroMeta}>{isAdmin?rows.length+" موظف · صافي المسير":"صافي مرتبك المتوقع"}</Text></View><View style={styles.heroBadge}><IconSymbol name="banknote" size={23} color="#F5F7FA"/></View></View>
  {isAdmin&&<View style={styles.actions}><Pressable onPress={()=>generate.mutate({month})} style={styles.primary}><Text style={styles.primaryText}>{generate.isPending?"جاري الحساب...":"حساب مسير الشهر"}</Text></Pressable><View style={styles.actionHint}><Text style={styles.hint}>يحسب الخصومات تلقائيًا من الغياب والتأخير.</Text></View></View>}
  <>{isAdmin&&<View style={styles.grid}><SurfaceCard style={styles.card}><Text style={styles.cardTitle}>Payroll 2.0 · تعديلات الشهر</Text><Row label="حوافز ومكافآت" value={formatMoney((adjustments.data??[]).filter(a=>a.type==="bonus"||a.type==="incentive").reduce((s,a)=>s+a.amount,0))}/><Row label="جزاءات وخصومات" value={formatMoney((adjustments.data??[]).filter(a=>a.type==="penalty"||a.type==="deduction").reduce((s,a)=>s+a.amount,0))}/><Row label="عدد التعديلات" value={String(adjustments.data?.length??0)}/></SurfaceCard><SurfaceCard style={styles.card}><Text style={styles.cardTitle}>السلف والقروض</Text><Row label="السلف النشطة" value={String((advances.data??[]).filter(a=>a.status==="active").length)}/><Row label="إجمالي المتبقي" value={formatMoney((advances.data??[]).filter(a=>a.status==="active").reduce((s,a)=>s+a.remainingAmount,0))}/><Text style={styles.smallHint}>إدارة السلف والحوافز من HR Tools.</Text></SurfaceCard></View>}</>{!isAdmin?<><View style={styles.grid}><SurfaceCard style={styles.card}><Text style={styles.cardTitle}>تفاصيل راتبك</Text><Row label="الأساسي" value={formatMoney(payrollInputsSafe(employee.baseSalary))}/><Row label="الأوفر تايم المعتمد" value={formatMoney(payroll.overtimeValue)}/><Row label="خصم الغياب" value={formatMoney(payroll.absenceDeduction)}/><Row label="خصم التأخير" value={formatMoney(payroll.lateDeduction)}/><Row label="الصافي" value={formatMoney(payroll.net)}/></SurfaceCard><SurfaceCard style={styles.card}><Text style={styles.cardTitle}>حالة المسير</Text><View style={styles.status}><View style={styles.ok}><IconSymbol name="checkmark" size={18} color="#34D399"/></View><View style={{flex:1}}><Text style={styles.statusTitle}>مسيرك تحت المراجعة</Text><Text style={styles.statusText}>سيظهر الاعتماد هنا بعد مراجعة الإدارة.</Text><StatusBadge label="قيد المراجعة" tone="warning" /></View></View></SurfaceCard></View></>:<><SectionTitle title="تفاصيل الموظفين" subtitle="اعتماد ومراجعة مسير الرواتب" />{rows.map(r=><View key={r.id} style={styles.rowCard}><View style={styles.person}><Text style={styles.personName}>{r.staffAccountId}</Text><Text style={styles.personMeta}>أساسي {formatMoney(r.baseSalary)}{r.overtime>0?` · أوفر تايم ${formatMoney(r.overtime)}`:""} · خصم {formatMoney(r.absenceDeduction+r.lateDeduction)}</Text></View><View style={styles.net}><Text style={styles.netValue}>{formatMoney(r.netSalary)}</Text><StatusBadge label={r.status==="approved"?"معتمد":"مسودة"} tone={r.status==="approved"?"success":"warning"} /></View><Pressable onPress={()=>r.status!=="approved"&&approve.mutate({id:r.id})} style={styles.approve}><Text style={styles.approveText}>{r.status==="approved"?"✓":"اعتماد"}</Text></Pressable></View>)}</>}
 </ScrollView></ScreenContainer>
}
function payrollInputsSafe(baseSalary:number){return baseSalary}
function Card({title,children}:{title:string,children:ReactNode}){return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>}
function Row({label,value}:{label:string,value:string}){return <View style={styles.row}><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>}
const styles=StyleSheet.create({content:{padding:22,paddingBottom:60,gap:14,maxWidth:1180,width:"100%",alignSelf:"center"},header:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},eyebrow:{color:"#97A3B6",fontSize:11,fontWeight:"800",textAlign:"right"},title:{color:"#EEF2F8",fontSize:30,fontWeight:"900",textAlign:"right"},sub:{color:"#97A3B6",fontSize:12,textAlign:"right",marginTop:5},icon:{width:52,height:52,borderRadius:17,backgroundColor:"#1B2A45",alignItems:"center",justifyContent:"center"},hero:{backgroundColor:"#0B1220",borderRadius:26,padding:24,flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},kicker:{color:"#93C5FD",fontSize:10,fontWeight:"900",textAlign:"right"},heroValue:{color:"#F5F7FA",fontSize:32,fontWeight:"900",textAlign:"right",marginTop:5},heroMeta:{color:"#8592A6",fontSize:11,textAlign:"right",marginTop:5},heroBadge:{width:58,height:58,borderRadius:18,backgroundColor:"#3B82F6",alignItems:"center",justifyContent:"center"},actions:{backgroundColor:"#131A24",borderWidth:1,borderColor:"#232C3A",borderRadius:18,padding:15,gap:10},primary:{backgroundColor:"#3B82F6",borderRadius:13,padding:14,alignItems:"center"},primaryText:{color:"#F5F7FA",fontWeight:"900"},actionHint:{alignItems:"flex-end"},hint:{color:"#97A3B6",fontSize:10},grid:{flexDirection:"row-reverse",gap:14},card:{flex:1,backgroundColor:"#131A24",borderWidth:1,borderColor:"#232C3A",borderRadius:20,padding:18},cardTitle:{color:"#EEF2F8",fontSize:16,fontWeight:"800",textAlign:"right",marginBottom:6},row:{flexDirection:"row-reverse",justifyContent:"space-between",paddingVertical:11,borderBottomWidth:1,borderBottomColor:"#1A212C"},label:{color:"#97A3B6",fontSize:11},value:{color:"#EEF2F8",fontSize:12,fontWeight:"800"},status:{flexDirection:"row-reverse",alignItems:"center",gap:10},ok:{width:40,height:40,borderRadius:13,backgroundColor:"#0F2A20",alignItems:"center",justifyContent:"center"},statusTitle:{color:"#EEF2F8",fontSize:12,fontWeight:"800",textAlign:"right"},statusText:{color:"#97A3B6",fontSize:10,textAlign:"right",marginTop:3},section:{fontSize:18,fontWeight:"900",color:"#EEF2F8",textAlign:"right"},rowCard:{backgroundColor:"#131A24",borderWidth:1,borderColor:"#232C3A",borderRadius:18,padding:14,flexDirection:"row-reverse",alignItems:"center",gap:10},person:{flex:1},personName:{color:"#EEF2F8",fontWeight:"900",textAlign:"right"},personMeta:{color:"#97A3B6",fontSize:10,textAlign:"right",marginTop:4},net:{alignItems:"flex-end"},netValue:{color:"#5B9BFF",fontWeight:"900"},pill:{fontSize:9,color:"#FBBF24",backgroundColor:"#2B2410",paddingHorizontal:8,paddingVertical:4,borderRadius:99,marginTop:3},approve:{backgroundColor:"#0B1220",paddingHorizontal:13,paddingVertical:9,borderRadius:11},approveText:{color:"#F5F7FA",fontSize:10,fontWeight:"800"},smallHint:{color:"#97A3B6",fontSize:10,textAlign:"right",marginTop:6},state:{flex:1,alignItems:"center",justifyContent:"center",gap:12}});
