import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { PageHeader, SectionTitle, SurfaceCard } from "@/components/ui/design-system";
import { trpc } from "@/lib/trpc";
const month=new Date().toISOString().slice(0,7);
export default function ReportsScreen(){
 const q=trpc.reports.month.useQuery({month});
 if(q.isLoading)return <ScreenContainer><View style={styles.state}><ActivityIndicator color="#2563EB"/><Text>جاري تجهيز التحليلات...</Text></View></ScreenContainer>;
 const d=q.data; const s=d?.summary??{staffCount:0,presentDays:0,absentDays:0,lateMinutes:0,pendingRequests:0};
 const attendance=s.presentDays+s.absentDays?Math.round((s.presentDays/(s.presentDays+s.absentDays))*100):0;
 return <ScreenContainer><ScrollView contentContainerStyle={styles.content}>
  <PageHeader eyebrow={`EXECUTIVE ANALYTICS · ${month}`} title="التقارير والتحليلات" subtitle="صورة تشغيلية سريعة عن الفريق والحضور والطلبات." icon="chart.bar.fill" />
  <View style={styles.hero}><View><Text style={styles.kicker}>TEAM HEALTH</Text><Text style={styles.heroValue}>{attendance}%</Text><Text style={styles.heroMeta}>معدل حضور مسجل هذا الشهر</Text></View><View style={styles.heroChart}>{[38,64,48,82,70,92,58].map((h,i)=><View key={i} style={[styles.chartBar,{height:h}]}/>)}</View></View>
  <View style={styles.kpis}><Kpi label="الموظفين" value={s.staffCount}/><Kpi label="أيام الحضور" value={s.presentDays}/><Kpi label="أيام الغياب" value={s.absentDays}/><Kpi label="طلبات معلقة" value={s.pendingRequests}/></View>
  <View style={styles.grid}><Card title="التأخير"><Text style={styles.big}>{s.lateMinutes}</Text><Text style={styles.caption}>دقيقة تأخير مسجلة للفريق</Text><Bar value={Math.min(100,Math.round(s.lateMinutes/10))}/></Card><Card title="الحضور مقابل الغياب"><Text style={styles.big}>{attendance}%</Text><Text style={styles.caption}>نسبة الحضور من السجلات المتاحة</Text><Bar value={attendance}/></Card></View>
  <SectionTitle title="أعلى مؤشرات التأخير" subtitle="الموظفون الذين يحتاجون متابعة تشغيلية" />
  {(d?.employees??[]).sort((a:any,b:any)=>b.lateMinutes-a.lateMinutes).slice(0,5).map((e:any)=><View style={styles.item} key={e.id}><View style={styles.itemMetric}><Text style={styles.metricValue}>{e.lateMinutes}</Text><Text style={styles.metricLabel}>دقيقة</Text></View><View style={{flex:1}}><Text style={styles.itemName}>{e.name}</Text><Text style={styles.itemMeta}>{e.department||"عام"} · {e.absentDays} غياب</Text></View></View>)}
 </ScrollView></ScreenContainer>
}
function Kpi({label,value}:{label:string,value:number}){return <View style={styles.kpi}><Text style={styles.kpiValue}>{value}</Text><Text style={styles.kpiLabel}>{label}</Text></View>}
function Card({title,children}:{title:string,children:React.ReactNode}){return <SurfaceCard style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</SurfaceCard>}
function Bar({value}:{value:number}){return <View style={styles.track}><View style={[styles.fill,{width:`${value}%` as const}]}/></View>}
const styles=StyleSheet.create({content:{padding:22,paddingBottom:60,gap:14,maxWidth:1180,width:"100%",alignSelf:"center"},header:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},eyebrow:{color:"#64748B",fontSize:10,fontWeight:"900",textAlign:"right"},title:{color:"#0F172A",fontSize:30,fontWeight:"900",textAlign:"right",marginTop:5},sub:{color:"#64748B",fontSize:12,textAlign:"right",marginTop:5},icon:{width:52,height:52,borderRadius:17,backgroundColor:"#DBEAFE",alignItems:"center",justifyContent:"center"},hero:{backgroundColor:"#0B1220",borderRadius:26,padding:24,flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},kicker:{color:"#93C5FD",fontSize:10,fontWeight:"900",textAlign:"right"},heroValue:{color:"#FFF",fontSize:34,fontWeight:"900",textAlign:"right"},heroMeta:{color:"#94A3B8",fontSize:10,textAlign:"right",marginTop:4},heroChart:{height:100,flexDirection:"row",alignItems:"flex-end",gap:7},chartBar:{width:10,borderRadius:8,backgroundColor:"#3B82F6"},kpis:{flexDirection:"row-reverse",gap:10},kpi:{flex:1,backgroundColor:"#FFF",borderWidth:1,borderColor:"#E2E8F0",borderRadius:17,padding:14},kpiValue:{fontSize:20,fontWeight:"900",color:"#0F172A",textAlign:"right"},kpiLabel:{fontSize:9,color:"#64748B",marginTop:4,textAlign:"right"},grid:{flexDirection:"row-reverse",gap:14},card:{flex:1,backgroundColor:"#FFF",borderWidth:1,borderColor:"#E2E8F0",borderRadius:20,padding:18},cardTitle:{fontSize:14,fontWeight:"900",color:"#0F172A",textAlign:"right"},big:{fontSize:30,fontWeight:"900",color:"#2563EB",textAlign:"right",marginTop:16},caption:{fontSize:10,color:"#64748B",textAlign:"right",marginTop:3},track:{height:9,borderRadius:99,backgroundColor:"#E2E8F0",marginTop:15,overflow:"hidden"},fill:{height:"100%",backgroundColor:"#2563EB",borderRadius:99},section:{fontSize:18,fontWeight:"900",color:"#0F172A",textAlign:"right"},item:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#E2E8F0",borderRadius:17,padding:14,flexDirection:"row-reverse",alignItems:"center",gap:12},itemName:{fontSize:12,fontWeight:"800",color:"#0F172A",textAlign:"right"},itemMeta:{fontSize:10,color:"#64748B",textAlign:"right",marginTop:3},itemMetric:{width:58,height:46,borderRadius:13,backgroundColor:"#EFF6FF",alignItems:"center",justifyContent:"center"},metricValue:{color:"#2563EB",fontSize:15,fontWeight:"900"},metricLabel:{color:"#64748B",fontSize:8},state:{flex:1,alignItems:"center",justifyContent:"center",gap:12}});
