import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { showAlert } from "@/lib/alert";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useAppData, type ScheduleEntry, type ShiftTemplate } from "@/lib/app-data";

const dayNames = ["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
function dateKey(date: Date) { return date.toISOString().slice(0,10); }
function makeWeek() { return Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);return {key:dateKey(d),label:i===0?"اليوم":dayNames[d.getDay()],date:new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short"}).format(d)};});}
function shiftLabel(s: ShiftTemplate|null|undefined) { if(!s)return "لم تحدد بعد"; if(s.kind==="weekly_off")return "إجازة أسبوعية"; return `${s.startTime} — ${s.endTime}${s.crossesMidnight?" · يوم جديد":""}`; }
function findSchedule(entries:ScheduleEntry[],staffId:string,day:string){return entries.find(e=>String(e.staffAccountId)===staffId&&e.scheduleDate===day);}
function tone(s:ShiftTemplate|null|undefined){if(!s)return {bg:"#F4F6F8",accent:"#98A6B8",text:"#667085"};if(s.kind==="weekly_off")return {bg:"#FFF7E8",accent:"#B7791F",text:"#8A5A12"};if(s.crossesMidnight)return {bg:"#F1EDFF",accent:"#7257C7",text:"#59449F"};return {bg:"#EAF3FF",accent:"#2F6DB3",text:"#1F5B96"};}

export default function ScheduleScreen(){
 const {role,employee,staffMembers,shiftTemplates,schedules,teamSchedules,saveSchedule}=useAppData();
 const week=useMemo(makeWeek,[]);
 const [selectedEmployee,setSelectedEmployee]=useState(staffMembers[0]?.id??employee.id);
 const [selectedDay,setSelectedDay]=useState(week[0].key); const [saving,setSaving]=useState(false);
 const visible=role==="manager"?teamSchedules:schedules;
 const member=staffMembers.find(m=>m.id===selectedEmployee);
 const entries=useMemo(()=>visible.filter(e=>String(e.staffAccountId)===selectedEmployee),[visible,selectedEmployee]);
 const assigned=entries.filter(e=>!!e.shift).length, off=entries.filter(e=>e.shift?.kind==="weekly_off").length, work=entries.filter(e=>e.shift&&e.shift.kind!=="weekly_off").length;
 async function assignShift(shift:ShiftTemplate){if(role!=="manager"||!selectedEmployee)return;setSaving(true);try{await saveSchedule({staffAccountId:Number(selectedEmployee),scheduleDate:selectedDay,shiftTemplateId:shift.id});showAlert("تم حفظ الجدول",`${member?.name??"الموظف"} — ${selectedDay}`);}catch(error){showAlert("تعذر حفظ الجدول",error instanceof Error?error.message:"حدث خطأ غير متوقع.");}finally{setSaving(false);}}
 return <ScreenContainer><FlatList data={week} keyExtractor={i=>i.key} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}
 ListHeaderComponent={<>
  <View style={styles.header}><View style={styles.headerCopy}><Text style={styles.eyebrow}>{role==="manager"?"إدارة الورديات":"مساحة العمل الشخصية"}</Text><Text style={styles.title}>الجدول</Text><Text style={styles.subtitle}>{role==="manager"?"وزّع ورديات الفريق وتابع تغطية الأسبوع من مكان واحد.":"راجع وردياتك وإجازاتك قبل بداية كل يوم."}</Text></View><View style={styles.icon}><IconSymbol name="calendar" size={24} color="#FFF"/></View></View>
  <View style={styles.hero}><View style={styles.heroTop}><Text style={styles.heroKicker}>هذا الأسبوع</Text><Text style={styles.badge}>{role==="manager"?"TEAM SCHEDULE":"MY SCHEDULE"}</Text></View><View style={styles.heroMain}><View style={styles.heroCopy}><Text style={styles.heroTitle}>{role==="manager"?"مركز تشغيل الورديات":"أسبوع عملك"}</Text><Text style={styles.heroText}>{role==="manager"?"اختار الموظف واليوم ثم عيّن الوردية المناسبة.":"كل مواعيدك اليومية وتفاصيل الوردية في شاشة واحدة."}</Text></View><View style={styles.heroNumber}><Text style={styles.heroNumberText}>{assigned}</Text><Text style={styles.heroNumberLabel}>مجدول</Text></View></View></View>
  <View style={styles.kpis}>{[[""+assigned,"أيام مجدولة"],[""+work,"أيام عمل"],[""+off,"إجازات"],[""+Math.max(0,7-assigned),"غير محدد"]].map(([v,l])=><View key={l} style={styles.kpi}><Text style={styles.kpiValue}>{v}</Text><Text style={styles.kpiLabel}>{l}</Text></View>)}</View>
  {role==="manager"&&<View style={styles.panel}><View style={styles.section}><View><Text style={styles.sectionTitle}>الفريق</Text><Text style={styles.sectionHint}>اختار موظفًا لإدارة جدوله</Text></View><Text style={styles.count}>{staffMembers.length}</Text></View><FlatList data={staffMembers} horizontal inverted showsHorizontalScrollIndicator={false} keyExtractor={i=>i.id} contentContainerStyle={styles.picker} renderItem={({item})=><Pressable onPress={()=>setSelectedEmployee(item.id)} style={[styles.employee,item.id===selectedEmployee&&styles.employeeActive]}><View style={[styles.avatar,item.id===selectedEmployee&&styles.avatarActive]}><Text style={styles.avatarText}>{item.name.slice(0,1)}</Text></View><Text style={[styles.employeeText,item.id===selectedEmployee&&styles.employeeTextActive]}>{item.name}</Text></Pressable>}/>{member&&<Text style={styles.selected}>إدارة جدول: {member.name}</Text>}</View>}
  {role==="manager"&&<View style={styles.assign}><View style={styles.section}><View><Text style={styles.assignTitle}>تعيين وردية</Text><Text style={styles.assignHint}>{week.find(d=>d.key===selectedDay)?.label} · {week.find(d=>d.key===selectedDay)?.date}</Text></View><Text style={styles.selectedBadge}>اليوم المحدد</Text></View><View style={styles.shiftButtons}>{shiftTemplates.map(s=>{const t=tone(s);return <Pressable key={s.id} disabled={saving} onPress={()=>assignShift(s)} style={[styles.shift,{backgroundColor:t.bg,borderColor:t.accent},saving&&styles.disabled]}><View style={[styles.dot,{backgroundColor:t.accent}]}/><Text style={[styles.shiftName,{color:t.text}]}>{s.name}</Text><Text style={[styles.shiftTime,{color:t.text}]}>{shiftLabel(s)}</Text><Text style={[styles.assignText,{color:t.accent}]}>{saving?"جارٍ الحفظ...":"تعيين"}</Text></Pressable>})}</View></View>}
  <View style={styles.section}><View><Text style={styles.sectionTitle}>أيام الأسبوع</Text><Text style={styles.sectionHint}>{role==="manager"?"اضغط على يوم لتحديده ثم اختر الوردية.":"تفاصيل كل يوم من أيام العمل."}</Text></View><Text style={styles.weekBadge}>7 أيام</Text></View>
 </>}
 renderItem={({item})=>{const entry=role==="manager"?findSchedule(visible,selectedEmployee,item.key):visible.find(e=>e.scheduleDate===item.key);const selected=item.key===selectedDay,t=tone(entry?.shift),today=item.key===week[0].key;return <Pressable onPress={()=>role==="manager"&&setSelectedDay(item.key)} style={[styles.day,today&&styles.today,selected&&role==="manager"&&styles.daySelected]}><View style={styles.dayTop}><View style={styles.dayMeta}>{today&&<Text style={styles.todayBadge}>اليوم</Text>}<Text style={styles.dayName}>{item.label}</Text><Text style={styles.dayDate}>{item.date}</Text></View><View style={styles.datePill}><Text style={styles.dateText}>{item.key.slice(-2)}</Text></View></View><View style={styles.divider}/>{entry?.shift?<View style={styles.assignedRow}><View style={[styles.marker,{backgroundColor:t.accent}]}/><View style={styles.assignedCopy}><View style={styles.assignedTitle}><Text style={styles.assignedName}>{entry.shift.name}</Text><Text style={[styles.status,{backgroundColor:t.bg,color:t.text}]}>{entry.shift.kind==="weekly_off"?"إجازة":"مجدول"}</Text></View><Text style={styles.assignedTime}>{shiftLabel(entry.shift)}</Text></View><View style={styles.check}><IconSymbol name="checkmark" size={16} color="#2F6DB3"/></View></View>:<View style={styles.empty}><View style={styles.emptyIcon}><IconSymbol name="clock" size={19} color="#98A6B8"/></View><View style={styles.emptyCopy}><Text style={styles.emptyTitle}>{role==="manager"?"لم يتم تعيين وردية":"لا توجد وردية محددة"}</Text><Text style={styles.emptyText}>{role==="manager"?"اختر هذا اليوم ثم عيّن وردية من لوحة التعيين.":"سيظهر موعد العمل هنا بمجرد اعتماده."}</Text></View></View>}</Pressable>}}
 ListFooterComponent={<View style={styles.footer}><Text style={styles.footerTitle}>ملاحظة تشغيلية</Text><Text style={styles.footerText}>الوردية المسائية التي تتجاوز منتصف الليل تُحسب على يوم بداية الوردية.</Text></View>}/></ScreenContainer>;
}

const styles=StyleSheet.create({
 content:{padding:20,paddingBottom:48,gap:14},header:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},headerCopy:{flex:1},eyebrow:{color:"#667085",fontSize:12,fontWeight:"700",textAlign:"right"},title:{color:"#172033",fontSize:30,fontWeight:"900",marginTop:4,textAlign:"right"},subtitle:{color:"#667085",fontSize:12,lineHeight:18,marginTop:5,textAlign:"right"},icon:{width:52,height:52,borderRadius:17,backgroundColor:"#163A63",alignItems:"center",justifyContent:"center",marginLeft:12},
 hero:{backgroundColor:"#102A47",borderRadius:24,padding:19,gap:16},heroTop:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},heroKicker:{color:"#9FB5CA",fontSize:10},badge:{backgroundColor:"#1E4771",color:"#B9D9F5",fontSize:8,fontWeight:"900",borderRadius:9,paddingHorizontal:9,paddingVertical:5},heroMain:{flexDirection:"row-reverse",alignItems:"center",gap:14},heroCopy:{flex:1},heroTitle:{color:"#FFF",fontSize:20,fontWeight:"900",textAlign:"right"},heroText:{color:"#B8C9D8",fontSize:11,lineHeight:18,marginTop:5,textAlign:"right"},heroNumber:{width:66,height:66,borderRadius:18,backgroundColor:"#173E65",alignItems:"center",justifyContent:"center"},heroNumberText:{color:"#72B5EF",fontSize:25,fontWeight:"900"},heroNumberLabel:{color:"#B8C9D8",fontSize:8},
 kpis:{flexDirection:"row-reverse",gap:8},kpi:{flex:1,backgroundColor:"#FFF",borderRadius:16,borderWidth:1,borderColor:"#E6EBF1",padding:12},kpiValue:{color:"#163A63",fontSize:21,fontWeight:"900",textAlign:"right"},kpiLabel:{color:"#667085",fontSize:9,marginTop:4,textAlign:"right"},
 panel:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#E6EBF1",borderRadius:19,padding:15},section:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},sectionTitle:{color:"#172033",fontSize:16,fontWeight:"900",textAlign:"right"},sectionHint:{color:"#98A6B8",fontSize:9,marginTop:3,textAlign:"right"},count:{minWidth:30,textAlign:"center",color:"#163A63",backgroundColor:"#EEF4FB",borderRadius:9,padding:7,fontSize:11,fontWeight:"900"},picker:{gap:8,paddingVertical:13},employee:{flexDirection:"row-reverse",alignItems:"center",gap:7,borderWidth:1,borderColor:"#E0E6ED",backgroundColor:"#FAFBFC",borderRadius:13,paddingHorizontal:11,paddingVertical:8},employeeActive:{backgroundColor:"#EEF4FB",borderColor:"#5A91C5"},avatar:{width:25,height:25,borderRadius:9,backgroundColor:"#E8EDF3",alignItems:"center",justifyContent:"center"},avatarActive:{backgroundColor:"#163A63"},avatarText:{color:"#667085",fontSize:10,fontWeight:"900"},employeeText:{color:"#667085",fontSize:10,fontWeight:"700"},employeeTextActive:{color:"#163A63",fontWeight:"900"},selected:{color:"#4D7FAF",fontSize:10,textAlign:"right"},
 assign:{backgroundColor:"#F7F9FC",borderRadius:19,padding:15,borderWidth:1,borderColor:"#E1E7EE"},assignTitle:{color:"#172033",fontSize:15,fontWeight:"900",textAlign:"right"},assignHint:{color:"#667085",fontSize:10,marginTop:3,textAlign:"right"},selectedBadge:{backgroundColor:"#EAF3FF",color:"#2F6DB3",fontSize:8,fontWeight:"900",borderRadius:9,paddingHorizontal:8,paddingVertical:5},shiftButtons:{flexDirection:"row-reverse",gap:8,marginTop:13},shift:{flex:1,minHeight:93,borderRadius:15,borderWidth:1,padding:11},dot:{width:8,height:8,borderRadius:4,marginBottom:8},shiftName:{fontSize:11,fontWeight:"900",textAlign:"right"},shiftTime:{fontSize:9,marginTop:5,textAlign:"right"},assignText:{fontSize:9,fontWeight:"900",marginTop:9,textAlign:"right"},disabled:{opacity:.55},weekBadge:{backgroundColor:"#F7F9FC",borderWidth:1,borderColor:"#E0E6ED",borderRadius:9,paddingHorizontal:9,paddingVertical:5,color:"#667085",fontSize:8,fontWeight:"900"},
 day:{backgroundColor:"#FFF",borderRadius:19,borderWidth:1,borderColor:"#E6EBF1",padding:15},today:{borderColor:"#A9CBEA"},daySelected:{borderColor:"#2F6DB3",borderWidth:2},dayTop:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},dayMeta:{alignItems:"flex-end",flex:1},todayBadge:{backgroundColor:"#EAF3FF",color:"#2F6DB3",borderRadius:7,paddingHorizontal:7,paddingVertical:3,fontSize:8,fontWeight:"900",marginBottom:5},dayName:{color:"#172033",fontSize:15,fontWeight:"900",textAlign:"right"},dayDate:{color:"#98A6B8",fontSize:10,marginTop:3,textAlign:"right"},datePill:{width:42,height:42,borderRadius:13,backgroundColor:"#F4F7FA",alignItems:"center",justifyContent:"center"},dateText:{color:"#31577F",fontSize:13,fontWeight:"900"},divider:{height:1,backgroundColor:"#EEF1F4",marginVertical:13},assignedRow:{flexDirection:"row-reverse",alignItems:"center",gap:10},marker:{width:5,height:46,borderRadius:3},assignedCopy:{flex:1},assignedTitle:{flexDirection:"row-reverse",alignItems:"center",gap:7},assignedName:{color:"#172033",fontSize:13,fontWeight:"900",textAlign:"right"},status:{borderRadius:7,paddingHorizontal:7,paddingVertical:3,fontSize:8,fontWeight:"900"},assignedTime:{color:"#667085",fontSize:11,marginTop:5,textAlign:"right"},check:{width:30,height:30,borderRadius:10,backgroundColor:"#EAF3FF",alignItems:"center",justifyContent:"center"},empty:{flexDirection:"row-reverse",alignItems:"center",gap:10},emptyIcon:{width:38,height:38,borderRadius:12,backgroundColor:"#F4F6F8",alignItems:"center",justifyContent:"center"},emptyCopy:{flex:1},emptyTitle:{color:"#667085",fontSize:12,fontWeight:"900",textAlign:"right"},emptyText:{color:"#98A6B8",fontSize:9,lineHeight:16,marginTop:3,textAlign:"right"},footer:{backgroundColor:"#F7F9FC",borderRadius:16,padding:14,borderWidth:1,borderColor:"#E0E6ED"},footerTitle:{color:"#31577F",fontSize:10,fontWeight:"900",textAlign:"right"},footerText:{color:"#667085",fontSize:10,lineHeight:17,marginTop:4,textAlign:"right"}
});