import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { trpc } from "@/lib/trpc";

export default function EmployeeSelfServiceScreen() {
  const month = new Date().toISOString().slice(0,7);
  const data = trpc.selfService.me.useQuery({ month }, { retry:false });
  const notifications = trpc.notifications.list.useQuery(undefined,{retry:false});
  const createRequest = trpc.requests.create.useMutation({ onSuccess:()=>data.refetch() });
  const [showRequest,setShowRequest] = useState(false);
  const [requestType,setRequestType] = useState<"إجازة"|"إجازة مرضية"|"إجازة طارئة"|"إذن"|"مأمورية">("إجازة");

  if(data.isLoading) return <ScreenContainer><View style={styles.state}><ActivityIndicator color="#163A63"/><Text style={styles.stateText}>جاري تحميل ملفك...</Text></View></ScreenContainer>;
  if(data.isError || !data.data) return <ScreenContainer><View style={styles.state}><Text style={styles.error}>تعذر تحميل ملف الموظف</Text><Text style={styles.stateText}>حاول تحديث الصفحة مرة أخرى.</Text></View></ScreenContainer>;

  const { staff, attendance, requests, payroll, leaveBalance } = data.data;
  const unread = (notifications.data ?? []).filter((n:any)=>!n.readAt).length;
  const current = attendance.filter((r:any)=>String(r.date).startsWith(month));
  const present = current.filter((r:any)=>r.status==="حاضر"||r.status==="متأخر").length;
  const late = current.reduce((s:number,r:any)=>s+Number(r.lateMinutes||0),0);
  const absent = current.filter((r:any)=>r.status==="غياب").length;
  const annual = Math.max(0,Number(leaveBalance?.annualDays??21)-Number(leaveBalance?.annualUsed??0));
  const sick = Math.max(0,Number(leaveBalance?.sickDays??14)-Number(leaveBalance?.sickUsed??0));
  const emergency = Math.max(0,Number(leaveBalance?.emergencyDays??6)-Number(leaveBalance?.emergencyUsed??0));
  const initials = staff.name.split(" ").map((x:string)=>x[0]).slice(0,2).join("");

  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={styles.avatar}><IconSymbol name="person.fill" size={23} color="#FFFFFF"/></View><View style={styles.headerCopy}><Text style={styles.eyebrow}>EMPLOYEE SELF-SERVICE</Text><Text style={styles.title}>ملفي</Text><Text style={styles.subtitle}>ملفك الوظيفي والحضور والطلبات والراتب في مكان واحد</Text></View></View>
    <View style={styles.profile}><View style={styles.profileAvatar}><Text style={styles.initials}>{initials}</Text></View><View style={styles.profileCopy}><Text style={styles.name}>{staff.name}</Text><Text style={styles.meta}>{staff.title || "موظف"} · {staff.department || "—"}</Text><Text style={styles.meta}>{staff.phone}</Text></View><View style={styles.badge}><Text style={styles.badgeText}>{staff.role==="employee"?"موظف":staff.role}</Text></View></View>

    <Section title={"ملخص الحضور · "+month}><View style={styles.grid}><Card icon="calendar" value={String(present)} label="أيام حضور"/><Card icon="clock" value={String(late)} label="دقائق تأخير"/><Card icon="calendar.badge.exclamationmark" value={String(absent)} label="غياب"/><Card icon="doc.text.fill" value={String(requests.filter((r:any)=>r.status==="قيد المراجعة").length)} label="طلبات معلقة"/></View></Section>
    <Section title="أرصدة الإجازات"><View style={styles.balanceRow}><Balance label="سنوية" value={annual} total={Number(leaveBalance?.annualDays??21)}/><Balance label="مرضية" value={sick} total={Number(leaveBalance?.sickDays??14)}/><Balance label="طارئة" value={emergency} total={Number(leaveBalance?.emergencyDays??6)}/></View></Section>

    <Section title="راتب الشهر"><View style={styles.payCard}><View style={styles.payTop}><View><Text style={styles.payLabel}>صافي المستحق</Text><Text style={styles.payValue}>{Number(payroll?.net??0).toLocaleString("ar-EG")} ج.م</Text></View><View style={styles.payIcon}><IconSymbol name="banknote" size={22} color="#FFFFFF"/></View></View><View style={styles.payGrid}><Pay label="الأساسي" value={Number(payroll?.baseSalary??0).toLocaleString("ar-EG")}/><Pay label="التأمينات" value={Number(payroll?.employeeSocialInsurance??0).toLocaleString("ar-EG")}/><Pay label="الضريبة" value={Number(payroll?.employeeIncomeTax??0).toLocaleString("ar-EG")}/><Pay label="الإضافات" value={Number(payroll?.totalAdjustments??0).toLocaleString("ar-EG")}/></View></View></Section>

    <View style={styles.sectionHead}><Text style={styles.sectionTitle}>الطلبات</Text><Pressable onPress={()=>setShowRequest(!showRequest)} style={styles.primary}><Text style={styles.primaryText}>+ طلب جديد</Text></Pressable></View>
    {showRequest && <View style={styles.composer}><Text style={styles.composerTitle}>إنشاء طلب HR</Text><View style={styles.typeRow}>{(["إجازة","إجازة مرضية","إجازة طارئة","إذن","مأمورية"] as const).map(t=><Pressable key={t} onPress={()=>setRequestType(t)} style={[styles.typeChip,requestType===t&&styles.typeChipActive]}><Text style={[styles.typeText,requestType===t&&styles.typeTextActive]}>{t}</Text></Pressable>)}</View><Text style={styles.hint}>سيتم إنشاء الطلب بتاريخ اليوم ويمكن استكمال التفاصيل من شاشة الطلبات.</Text><Pressable disabled={createRequest.isPending} onPress={()=>{const d=new Date().toISOString().slice(0,10);createRequest.mutate({type:requestType,fromDate:d,toDate:d,reason:"طلب مقدم من الخدمة الذاتية"})}} style={styles.submit}><Text style={styles.submitText}>{createRequest.isPending?"جاري الإرسال...":"إرسال الطلب"}</Text></Pressable></View>}
    <View style={styles.list}>{requests.slice(0,6).map((r:any)=><View key={r.id} style={styles.request}><View style={styles.requestIcon}><IconSymbol name="doc.text.fill" size={15} color="#163A63"/></View><View style={styles.requestCopy}><Text style={styles.requestType}>{r.type}</Text><Text style={styles.requestMeta}>{r.fromDate} {r.toDate!==r.fromDate?"— "+r.toDate:""}</Text></View><Text style={[styles.status,r.status==="مقبول"?styles.accepted:r.status==="مرفوض"?styles.rejected:styles.pending]}>{r.status}</Text></View>)}{!requests.length&&<Text style={styles.empty}>لا توجد طلبات حتى الآن.</Text>}</View>

    <Section title="آخر الحضور"><View style={styles.list}>{attendance.slice(0,7).map((r:any)=><View key={r.id} style={styles.attRow}><Text style={styles.attDate}>{r.date}</Text><View style={styles.attCenter}><Text style={styles.attStatus}>{r.status}</Text><Text style={styles.attMeta}>{r.checkIn||"—"} → {r.checkOut||"—"}</Text></View><Text style={styles.attLate}>{Number(r.lateMinutes||0)} د</Text></View>)}</View></Section>
    <View style={styles.notice}><IconSymbol name="notifications" size={18} color="#163A63"/><View style={styles.noticeCopy}><Text style={styles.noticeTitle}>{unread?String(unread)+" إشعار غير مقروء":"لا توجد إشعارات جديدة"}</Text><Text style={styles.noticeText}>الموافقات والتحديثات الخاصة بحسابك تظهر هنا وفي شاشة الإشعارات.</Text></View></View>
  </ScrollView></ScreenContainer>;
}

function Section({title,children}:{title:string;children:any}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}

function Card({icon,value,label}:{icon:any,value:string,label:string}){return <View style={styles.card}><IconSymbol name={icon} size={19} color="#163A63" /><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>}
function Balance({label,value,total}:{label:string,value:number,total:number}){const p=total?Math.round(value/total*100):0;return <View style={styles.balance}><Text style={styles.balanceLabel}>{label}</Text><Text style={styles.balanceValue}>{value}</Text><Text style={styles.balanceTotal}>متبقي من {total}</Text><View style={styles.track}><View style={[styles.fill,{width:`${p}%`}]} /></View></View>}

const styles=StyleSheet.create({
 state:{flex:1,alignItems:"center",justifyContent:"center",gap:10},stateText:{fontSize:11,color:"#667085"},error:{fontSize:17,fontWeight:"900",color:"#B54747"},
 content:{padding:20,paddingBottom:50,gap:16},header:{flexDirection:"row-reverse",alignItems:"center",gap:13},avatar:{width:46,height:46,borderRadius:15,backgroundColor:"#163A63",alignItems:"center",justifyContent:"center"},headerCopy:{flex:1},eyebrow:{fontSize:9,fontWeight:"800",color:"#6B7A8C",textAlign:"right",letterSpacing:1},title:{fontSize:28,fontWeight:"900",color:"#172033",textAlign:"right"},subtitle:{fontSize:11,color:"#667085",textAlign:"right",marginTop:2},profile:{backgroundColor:"#163A63",borderRadius:22,padding:18,flexDirection:"row-reverse",alignItems:"center",gap:13},profileAvatar:{width:62,height:62,borderRadius:20,backgroundColor:"#31577F",alignItems:"center",justifyContent:"center"},initials:{fontSize:20,fontWeight:"900",color:"#fff"},profileCopy:{flex:1},name:{fontSize:18,fontWeight:"900",color:"#fff",textAlign:"right"},meta:{fontSize:10,color:"#D9E6F2",textAlign:"right",marginTop:3},badge:{backgroundColor:"rgba(255,255,255,.14)",paddingHorizontal:10,paddingVertical:7,borderRadius:10},badgeText:{fontSize:9,fontWeight:"800",color:"#fff"},section:{gap:10},sectionTitle:{fontSize:14,fontWeight:"900",color:"#172033",textAlign:"right"},grid:{flexDirection:"row-reverse",flexWrap:"wrap",gap:10},card:{width:"48%",backgroundColor:"#fff",borderWidth:1,borderColor:"#E8EDF3",borderRadius:18,padding:15,gap:6},value:{fontSize:22,fontWeight:"900",color:"#172033",textAlign:"right"},label:{fontSize:10,fontWeight:"700",color:"#667085",textAlign:"right"},balanceRow:{flexDirection:"row-reverse",gap:10},balance:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:"#E8EDF3",borderRadius:17,padding:13},balanceLabel:{fontSize:10,fontWeight:"800",color:"#667085",textAlign:"right"},balanceValue:{fontSize:24,fontWeight:"900",color:"#163A63",textAlign:"right",marginTop:4},balanceTotal:{fontSize:9,color:"#98A6B8",textAlign:"right"},track:{height:5,backgroundColor:"#EEF2F6",borderRadius:4,marginTop:9,overflow:"hidden"},fill:{height:5,backgroundColor:"#6FA9D8",borderRadius:4},request:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E8EDF3",borderRadius:15,padding:12,flexDirection:"row-reverse",alignItems:"center",gap:10},requestIcon:{width:34,height:34,borderRadius:11,backgroundColor:"#F2F5F8",alignItems:"center",justifyContent:"center"},requestCopy:{flex:1},requestType:{fontSize:11,fontWeight:"800",color:"#172033",textAlign:"right"},requestMeta:{fontSize:9,color:"#98A6B8",textAlign:"right",marginTop:3},status:{fontSize:9,fontWeight:"800",color:"#31577F"},accepted:{color:"#16805A"},rejected:{color:"#B54747"},empty:{fontSize:11,color:"#98A6B8",textAlign:"right"},notice:{backgroundColor:"#F2F5F8",borderWidth:1,borderColor:"#D9E6F2",borderRadius:17,padding:14,flexDirection:"row-reverse",gap:10,alignItems:"center"},noticeCopy:{flex:1},noticeTitle:{fontSize:11,fontWeight:"800",color:"#163A63",textAlign:"right"},noticeText:{fontSize:10,color:"#667085",textAlign:"right",marginTop:3}
});
